language: scala

sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

scala:
  - 2.12.7

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

install: true

script:
  - sbt clean coverage test coverageReport

after_success:
  - sbt coverageReport coveralls
