sudo: false

jdk:
  - oraclejdk11

addons:
  apt:
    packages:
      - oracle-java11-installer

language: scala

scala:
  - 2.12.7

services:
  - xvfb

before_install:
  - export DISPLAY=:99.0

install: true

script:
  - sbt clean coverage test coverageReport

after_success:
  - sbt coverageReport coveralls
